# Add this description above jobs:
env:
  NEXT_PUBLIC_BASE_URL: ${{secrets.NEXT_PUBLIC_BASE_URL}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate
        run: npm run generate
      # Uncomment the following if needed
      # - name: Zip artifact for upload
      #   run: cd dist && zip ../dist.zip . -r
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: out # Replace 'dist' with 'out'
